// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciamentoTimesAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250527002430_AtualizacaoModelo")]
    partial class AtualizacaoModelo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("TimeEsportivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoFundacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroJogadores")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TimesEsportivos");
                });
#pragma warning restore 612, 618
        }
    }
}
